# Authentitation
JWT_ACCESS_TOKEN_SECRET=
JWT_REFRESH_TOKEN_SECRET=
# Mail
MAIL_USERNAME=
MAIL_PASSWORD=
# Database
DATABASE_USER=
DATABASE_PASS=
DATABASE_HOST=
DATABASE_NAME=
# Google Sheets
SERVICE_ACCOUNT_CREDENTIALS=credentials.json
SPREADSHEET_ID=
